name: Quire
on:
  push:
    branches:
      - master
permissions:
  actions: read
  checks: read
  contents: write
  deployments: write
  pull-requests: write
  repository-projects: write
  statuses: write
jobs:
  verification:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: echo hello
        run: echo "Hello, world!"
